export  { default as Heading } from "./Heading/Heading"
export  { default as Banner } from "./Banner"
export  { default as Contact } from "./Contact"
export  { default as BannerLanding } from "./BannerLanding"
export  { default as ProjectBanner } from "./ProjectBanner"
export  { default as Services } from "./Services"